plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

group = 'dev.nixoly'
version = '1.0.6'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenCentral()
    maven { url = 'https://jitpack.io' }
    maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url = 'https://oss.sonatype.org/content/repositories/snapshots/' }
    maven { url = 'https://repo.codemc.io/repository/maven-releases/' }
}

dependencies {
    compileOnly 'org.spigotmc:spigot-api:1.16.5-R0.1-SNAPSHOT'
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
    implementation 'com.github.Anon8281:UniversalScheduler:0.1.6'
    implementation("org.bstats:bstats-bukkit:3.2.1")
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'net.kyori:adventure-platform-bukkit:4.3.2'
    implementation 'net.kyori:adventure-text-minimessage:4.13.1'
}

shadowJar {
    archiveClassifier.set('')
    mergeServiceFiles()
    relocate 'org.bstats', 'dev.nixoly.libs.bstasts'
    relocate 'com.github.Anon8281.universalScheduler', 'dev.nixoly.libs.universalscheduler'
    relocate 'com.google.gson', 'dev.nixoly.libs.gson'
    relocate 'net.kyori', 'dev.nixoly.libs.kyori'
}

jar {
    enabled = false
}

tasks.register('copyShadowJar', Copy) {
    from(tasks.shadowJar)
    into("${rootDir}/buildJar")
}

tasks.clean {
    delete "${rootDir}/buildJar"
}

tasks.shadowJar {
    finalizedBy tasks.copyShadowJar
}

tasks.build.dependsOn tasks.copyShadowJar

processResources {
    filesMatching('plugin.yml') {
        expand 'version': version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
