name: FireworkBlockInteractFix
version: '${version}'
main: dev.nixoly.fireworkblockinteractfix.FireworkBlockInteractFix
api-version: '1.16'
authors: [ Nixoly ]
description: If you right-click a firework rocket while your crosshair is on a cobweb, the rocket spawns on that cobweb and shoots upward instead of boosting elytra (works on the ground and while gliding).
